### ISSUE TITLE
React router v4?

### ISSUE THREAD

**Issue by jwamsterdam** [kuuup/mobx-ssr-example#3]
Thnx for this repo!

Don't know why react router was removed, but would be great if the new react router (v4) could be added to the solution.

Many thnx in advance!

**Comment by kuuup-at-work** [comment]
I removed react-router because I don't use it in my projects anymore. However, maybe I'll have a look.

**Comment by jwamsterdam** [comment]
Hi kuuup, that would be really awesome! Looking forward to it, and hope you find the time!

**Comment by kuuup** [comment]
Hi.
There is a react-router branch now. Please do a checkout and close this ticket if this branch is what you're looking for.

**Comment by jwamsterdam** [comment]
Hi kuuup, many thnx for the react router branch! Will look into it this weekend!

**Comment by jwamsterdam** [comment]
hmmm. get get it to work.. when I run npm start, it waits at node src/index.js
If I then go to 127.0.0.1:3000 I get the following in my console:

> C:\mobx-ssr-example-react-router>npm start
> 
> > mobx-ssr-example@2.0.0 start C:\mobx-ssr-example-react-router
> > node src/index.js
> 
> server-side
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: ENOENT: no such file or directory, open 'C:\mobx-ssr-example-react-router\dist\bundle.js'
> 
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
> npm ERR! node v7.4.0
> npm ERR! npm  v4.0.5
> npm ERR! code ELIFECYCLE
> npm ERR! mobx-ssr-example@2.0.0 start: `node src/index.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the mobx-ssr-example@2.0.0 start script 'node src/index.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the mobx-ssr-example package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node src/index.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs mobx-ssr-example
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls mobx-ssr-example
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\mobx-ssr-example-react-router\npm-debug.log
> 
> C:\mobx-ssr-example-react-router>

can you help me out? thank you!

**Comment by kuuup** [comment]
Did you execute `npm run build:client`? Is there a bundle.js in `dist/`?

**Comment by jwamsterdam** [comment]
ah great!!! I ran npm run build. forgot the :client at the end. It is working great, many thanks for your quick reply!

**Comment by kuuup** [comment]
You're welcome 😃

**Comment by jwamsterdam** [comment]
Hi kuuup, I did notice some small differences compared to my current stack, e.g. create-react-app, where create-react-app for instance creates the bundle.js name with a random number postfix so you wont have to clear caches (at clients) all the time. Did you use create-react-app as a starting point, or did you go from scratch?

**Comment by kuuup** [comment]
This project was from scratch. I didn't care about caches, css or other real life stuff to keep it simple. But it should be easy to adapt certain parts to your needs.

**Comment by jwamsterdam** [comment]
Great kuuup, will look into it further! this is really of great help! btw. I know this is quite offtopic, but can you help me in the right direction on finding hosting for a React SSR app? I heard a lot about heroku, but I cant find the info on how to host SSR apps... many thanks already!

**Comment by kuuup-at-work** [comment]
Sorry, but I have no idea. I host my stuff on my own server.
