### ISSUE TITLE
Updating the data from the server side

### ISSUE THREAD

**Issue by picazi** [kuuup/mobx-ssr-example#4]
Hi and thanks for your ssr example,

I was wondering how it's possible to update the data from server side and not from the client. 

I want to create an app with your boilerplate, which fetches data from different websites or other sources and updates the client from server side. If I try to update the AppState on the server (with a simple setTimeout and run appstate.addItem('foobar'); after 5 secs) I receive the following message:

`Warning: forceUpdate(...): Can only update a mounting component. This usually means you called forceUpdate() outside componentWillMount() on the server. This is a no-op. Please check the code for the Root component.`

How is it possible to update the data on the server?
I want to use a store class and add new data e.g. to an array and the client should update automatically...

Thanks.

**Comment by kuuup** [comment]
Hi.

Please send me an example of your code because I'm not sure what you're trying to do.

When you render your app on the server you could persist your state but the react components only exist to render them into a string. When the request is finished they are gone and can't be updated by the store. That's why you get a warning.
So you need to re-render your app by sending a request from a client. Now the state can be calculated again (this is the place you could add "foobar" to the store).

If you just add new value after 5 seconds nothing will happen if you don't have a mechanism to push state updates to your client (see socket.io).

**Comment by picazi** [comment]
Hi,
thanks for your fast reply!
You said the client have to send a request. But what if the client can't send a request, the server has to notify the clients.. Then I have to use sockets, right?

I have a few modules which can get the weather, news or emails and so on. 
In the module constructor I am creating a component and adding the mobx datastore: 

```
import React from 'react';
import Module from '../../core/domain/module_class';
import NewsHelper from './mod_news_helper';
import NewsStore from './mod_news_store';
import NewsComponent from './mod_news_component';

class News extends Module {
	/**
	 * Constructor for the News module. Is extended from the parent class module.js.
	 * @param  {Object} config    The module config with all important module parameters
	 * @param  {Object} datastore The local datastore for this module
	 */
	constructor(config, modulepath, modulefiles) {
		super(config, modulepath, modulefiles);

		this.helper = new NewsHelper(config);
		this.datastore = new NewsStore();
		this.component = <NewsComponent store={this.datastore} />;
		// this.component = React.createFactory(NewsComponent);
		// this.component = React.createFactory(NewsComponent);
	}
}

export default News;
```

```
import { observable, action } from 'mobx';

class NewsStore {
     @observable data = [];

     @action
     add(data) {
         console.log('data added! -> ' + data);
         this.data.push(data);
     }
}

export default NewsStore;
```

The module can send new data directly to the datastore with: `this.datastore.add('foorbar')`

My goal was it to publish new data to a data model (this.datastore) and let react handle the updates. In the react root component I want to dynamically add all components with the datastore from the instanced modules and render the page. If the module gets an update, I can update the datastore with this.datastore.add('foobar') and the component should re-render the page. 

But if I understand you correctly, this is not possible with react and mobx. 
I have use sockets to update the client?

Thanks.

**Comment by kuuup-at-work** [comment]
Right, neither react nor mobx provide a way to push your state to the client. There are different ways to achieve pushing state and using socket.io is just one of them.

**Comment by picazi** [comment]
I used socket.io, but I have to figure out how to use it with react.
What are the other different ways? Do you have a keyword for me.
Thanks for pointing me in the right direction.

**Comment by kuuup-at-work** [comment]
Hi.
You should read about Service Workers and the [Push API](http://w3c.github.io/push-api/). You could even use some kind of polling to get updates in your client.
When you have chosen a way to push state to your client you must update your mobx observables and your react components will refresh.

**Comment by kuuup** [comment]
Take a look at the socket branch for an example.

**Comment by picazi** [comment]
Wow awesome this branch is new!
Cool, thank you very much! This will help me a lot!
